### PR TITLE
Jtromero/sync frontend

### PR DESCRIPTION
**Pull request by jacksontromero**
### useContext
* Global data on the fronted is stored in React context objects that are created in src/contexts
* Each context should ***never*** be updated by an individual component, and will instead be updated by a webSocket from the server
* This means that components don't need to worry about getting up to date information anymore!
* Example: Adding a new question
  1. Student uses "Add Question" button which calls the "/addQuestion" route
  2. Server adds question to queue
  3. Server sends up to date StudentDataContext to that student
  4. Server sends up to date AllStudentsContext to TAs
  5. (not implemented yet) Server sends up to date QueueDataContext to all users for accurate statistics/wait time estimates

Using contexts like this means that properties don't need to be passed down in the 'props' field anymore and the same variables will be consistent across all components (you wouldn't believe how many different things were stuffed in queueData by different components/API routes before)

---

### Not finished yet
* Issue with updating queue topics, although I'm pretty sure it existed beforehand.  Described in QueueTopicSettings.tsx

### CODE REVIEW

**Comment by pranavaddepalli** [comment]
World's largest PR

**Comment by angelaz1** [comment]
(Realized I forgot to follow up here) 
Everything functionality-wise so far seems to be working on my end when I clicked through everything; I can take a closer look at the code itself later today

**Review by pranavaddepalli — COMMENTED** [review]
.

**Comment by pranavaddepalli** [comment]
Everything also seems to be working on my end. I saw a lot of socket stuff was moved and it seems to work on my side with two browsers, but I guess we'll see how it goes with a ton of students over the semester

**Review by pranavaddepalli — APPROVED** [review]

**Comment by pranavaddepalli** [comment]
@angelaz1 or @amandaLi7 could you review as well before merge

**Comment by pranavaddepalli** [comment]
@amandaLi7 and I have discovered that for some reason, in this branch, you can't add topics...

- csv upload does not work (but might get fixed by #204 ? not sure) but it does add to the database. nothing shows up in the settings and students cannot see the topic
- manually adding a topic allows it to show up on the settings page, but with "Invalid DateTime." However these topics do correctly show up for students
image

**Review by amandaLi7 — APPROVED** [review]
lgtm! I briefly glanced at the code as well. Some things to be addressed:
- notifications for student joining queue and reminder after helping for _ minutes isn't showing up for me, but that could just be me
- upload csv doesn't work yet

ty Jackson

**Comment by amandaLi7** [comment]
also, I forgot to mention: for me locally, I can't add myself to 2 separate semesters for some reason. It works for Pranav, so I might just be the odd one out. If it works for others, then it should be ok, but putting it here for something to review while testing locally.

**Comment by jacksontromero** [comment]
@amandaLi7 I got queue join notifications working.  As far as I can tell the "remind me after _" never worked to begin with so that's a separate issue.  I was also able to add myself to two semesters so I don't know what that issue was with you

@pranavaddepalli Your PR didn't fix whatever issue I caused with the CSV uploads.  Could you take a look at it, I'm not familiar with how the file upload stuff works?

**Comment by pranavaddepalli** [comment]
yeah that was never a thing, notifications don't actually work lol

taking a look at csv now

**Comment by pranavaddepalli** [comment]
@amandaLi7 if u r having issues with adding yourself to the W22 semester, try running the following sql statement on ur local psql instance:

`INSERT INTO semester VALUES ('W22', '1-1-23', '1-1-23');`

**Comment by pranavaddepalli** [comment]
the issue is caused by lines 80/81 in home.js. queueData.topics is used in two different areas:
1. to show the topics for a question (date-dependent)
2. to show all the topics in the sem (not date-dependent)

Lines 80/81 filter all the topics to those that have an overlap with today, which are effectively the "current topics,"  and puts it in queueData. This works for questions, but the topics that show up on the settings page are only the ones that are ongoing. So, we can't just delete this filter.

We can either keep all topics in queueData and move the filtering logic to the topics dropdown, but this is sus / bad. I think a better way is to change where the settings page is getting its data from and just having it pull straight from the database (i.e., add something like `get_all_topics` into settings.js and having that be the source for the settings page

**Review by amandaLi7 — APPROVED** [review]
looks good! csv file upload and notifications are working :)

this might be a separate issue, but we need to grab the questionsURL from settings and add that to the UpdateQuestionOverlay. I tried to do it but it's not refreshing for me for some reason. I can open up an issue or if you have time to add it, either way works for me.

**Comment by jacksontromero** [comment]
@amandaLi7 Fixed it, good to merge?

**Comment by amandaLi7** [comment]
YAS perf. We need a meeting where you talk about literally everything new about the ecosystem. I had no idea there's a diff between QueueSettingsContext and QueueDataContext.

**Comment by pranavaddepalli** [comment]
image

**Review by pranavaddepalli — APPROVED** [review]

**Pull request merged**
